name: CI Test
on:
  push:
    paths:
      - 'src/**'

jobs:
  ci_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload jar
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "rankup"
          automatic_release_tag: "rankup"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rankup Artifact
          path: build/libs/*.jar
